name: Virceli
options:
  minimumXcodeGenVersion: 2.40.0
  createIntermediateGroups: true
packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: 1.11.0
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 14.0
    PRODUCT_BUNDLE_IDENTIFIER: com.virceli.app
    PRODUCT_NAME: Virceli
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Virceli
    INFOPLIST_KEY_CFBundleIconFile: AppIcon
    INFOPLIST_KEY_NSHighResolutionCapable: YES
targets:
  Virceli:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
      - path: Resources/UnityPlayer/AvatarUnity.app
      - path: public
    dependencies:
      - package: SwiftTerm
        product: SwiftTerm
    postBuildScripts:
      - name: Embed Unity Player App
        inputFiles:
          - $(PROJECT_DIR)/Resources/UnityPlayer/AvatarUnity.app
          - $(PROJECT_DIR)/Resources/AppIcon.icns
        outputFiles:
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/UnityPlayer/AvatarUnity.app
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/AppIcon.icns
        script: |
          set -euo pipefail
          SRC_APP="${PROJECT_DIR}/Resources/UnityPlayer/AvatarUnity.app"
          DST_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/UnityPlayer"
          DST_APP="${DST_DIR}/AvatarUnity.app"

          if [ ! -d "${SRC_APP}" ]; then
            echo "warning: Unity app not found at ${SRC_APP}"
            exit 0
          fi

          mkdir -p "${DST_DIR}"
          rm -rf "${DST_APP}"
          cp -R "${SRC_APP}" "${DST_APP}"

          if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}" ]; then
            /usr/bin/codesign --force --deep --sign "${EXPANDED_CODE_SIGN_IDENTITY}" "${DST_APP}" || true
          else
            /usr/bin/codesign --force --deep --sign - "${DST_APP}" || true
          fi

          ICON_SRC="${PROJECT_DIR}/Resources/AppIcon.icns"
          ICON_DST="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/AppIcon.icns"
          if [ -f "${ICON_SRC}" ]; then
            cp -f "${ICON_SRC}" "${ICON_DST}"
            /usr/libexec/PlistBuddy -c "Set :CFBundleIconFile AppIcon" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" || \
              /usr/libexec/PlistBuddy -c "Add :CFBundleIconFile string AppIcon" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          fi

          echo "Embedded Unity app -> ${DST_APP}"
    settings:
      base:
        PRODUCT_MODULE_NAME: ClaudeNativeMac
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
schemes:
  Virceli:
    build:
      targets:
        Virceli: all
    run:
      config: Debug
    archive:
      config: Release
