name: Bug report
description: Report a reproducible problem in Virceli
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue. Please include clear repro steps.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
      placeholder: Briefly describe the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Virceli version
      description: Tag or commit hash
      placeholder: v0.1.0 or commit SHA
    validations:
      required: true
  - type: input
    id: macos
    attributes:
      label: macOS version
      description: "Example: Tahoe 26.2"
      placeholder: macOS version
    validations:
      required: true
  - type: dropdown
    id: claude_cli
    attributes:
      label: Claude Code CLI status
      options:
        - Installed and authenticated
        - Installed but not authenticated
        - Not installed / not sure
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Numbered steps are best.
      placeholder: |
        1. Open app
        2. Select workspace
        3. Launch Claude Code
        4. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or attach screenshots.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I confirmed this issue is reproducible.
          required: true
        - label: I checked existing issues before submitting.
          required: true
